#include <windows.h>

#define PROJECT_NAME                    "Traymond"
#define PROJECT_NAME_LC                 "traymond"
#define PROJECT_NAME_UC                 "TRAYMOND"
#define POPUP_CLASS                     "POPUP_WINDOW"
#define IDC_STATIC                      -1
#define IDM_EXIT                        1
#define IDM_RESTORE_ALL_WINDOWS         2
#define IDM_OPTIONS                     3
#define IDM_RESTORE_LAST_WINDOW         4
#define IDC_NEW                         11
#define IDC_SAVE                        12
#define IDC_REMOVE                      13
#define IDD_OPTIONS                     101
#define IDD_RULES                       103
#define IDD_ICONS                       104
#define IDI_TRAYMOND                    201
#define IDC_HOTKEY                      1000
#define IDC_HOTKEY_LIST                 1001
#define IDC_CHECK_USE_WIN               1002
#define IDC_CHECK_AUTORUN               1003
#define IDC_COMBO_HIDE_TYPE             1004
#define IDM_POPUP                       1005
#define IDC_LIST_RULES                  1005
#define IDC_CHECK_AUTO_HIDING           1006
#define IDC_BUTTON_RULES                1007
#define IDC_EDIT_TEXT                   1009
#define IDC_EDIT_CLASS                  1010
#define IDC_EDIT_PATH                   1011
#define IDC_CHECK_REGEX_TEXT            1012
#define IDC_CHECK_REGEX_CLASS           1013
#define IDC_CHECK_REGEX_PATH            1014
#define IDC_EDIT_NAME                   1015
#define IDC_COMBO_WINDOWS               1016
#define IDC_ICON_LIST                   1019
